// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DeviceCreate
 */
export type DeviceCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * DeviceHandshakePublic
 */
export type DeviceHandshakePublic = {
    device: DevicePublic;
    /**
     * Server Time
     */
    server_time: string;
};

/**
 * DeviceNotePublic
 */
export type DeviceNotePublic = {
    /**
     * Delivery Id
     */
    delivery_id: string;
    /**
     * Note Id
     */
    note_id: string;
    /**
     * Text
     */
    text: string;
    /**
     * Min Retention Seconds
     */
    min_retention_seconds: number;
    /**
     * Max Retention Seconds
     */
    max_retention_seconds?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Queue Remaining
     */
    queue_remaining: number;
    /**
     * Server Time
     */
    server_time: string;
};

/**
 * DevicePublic
 */
export type DevicePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Last Seen At
     */
    last_seen_at?: string | null;
};

/**
 * DeviceRegistrationInfo
 */
export type DeviceRegistrationInfo = {
    /**
     * Api Url
     */
    api_url: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Token
     */
    token: string;
    /**
     * Name
     */
    name: string;
};

/**
 * DeviceUpdate
 */
export type DeviceUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * DevicesPublic
 */
export type DevicesPublic = {
    /**
     * Data
     */
    data: Array<DevicePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * NoteCreate
 */
export type NoteCreate = {
    /**
     * Text
     */
    text: string;
    /**
     * Recipient Id
     */
    recipient_id: string;
    /**
     * Min Retention
     */
    min_retention?: string;
    /**
     * Max Retention
     */
    max_retention?: string | null;
};

/**
 * NoteDeliveryPublic
 */
export type NoteDeliveryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Device Name
     */
    device_name: string;
    /**
     * Received
     */
    received: boolean;
    /**
     * Received At
     */
    received_at?: string | null;
};

/**
 * NoteDetailPublic
 */
export type NoteDetailPublic = {
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: string;
    /**
     * Sender Id
     */
    sender_id: string;
    /**
     * Recipient Id
     */
    recipient_id: string;
    /**
     * Recipient Name
     */
    recipient_name?: string | null;
    /**
     * Sender Name
     */
    sender_name?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Min Retention Seconds
     */
    min_retention_seconds: number;
    /**
     * Max Retention Seconds
     */
    max_retention_seconds?: number | null;
    /**
     * Delivered Count
     */
    delivered_count?: number;
    /**
     * Received Count
     */
    received_count?: number;
    /**
     * Deliveries
     */
    deliveries?: Array<NoteDeliveryPublic>;
};

/**
 * NotePublic
 */
export type NotePublic = {
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: string;
    /**
     * Sender Id
     */
    sender_id: string;
    /**
     * Recipient Id
     */
    recipient_id: string;
    /**
     * Recipient Name
     */
    recipient_name?: string | null;
    /**
     * Sender Name
     */
    sender_name?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Min Retention Seconds
     */
    min_retention_seconds: number;
    /**
     * Max Retention Seconds
     */
    max_retention_seconds?: number | null;
    /**
     * Delivered Count
     */
    delivered_count?: number;
    /**
     * Received Count
     */
    received_count?: number;
};

/**
 * NotesPublic
 */
export type NotesPublic = {
    /**
     * Data
     */
    data: Array<NotePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Partner Id
     */
    partner_id?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserSearchResult
 */
export type UserSearchResult = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Partner Id
     */
    partner_id?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * UsersSearchPublic
 */
export type UsersSearchPublic = {
    /**
     * Data
     */
    data: Array<UserSearchResult>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersSearchUsersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
    };
    url: '/api/v1/users/search';
};

export type usersSearchUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersSearchUsersError = usersSearchUsersErrors[keyof usersSearchUsersErrors];

export type usersSearchUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersSearchPublic;
};

export type usersSearchUsersResponse = usersSearchUsersResponses[keyof usersSearchUsersResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type devicesReadDevicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/devices/';
};

export type devicesReadDevicesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesReadDevicesError = devicesReadDevicesErrors[keyof devicesReadDevicesErrors];

export type devicesReadDevicesResponses = {
    /**
     * Successful Response
     */
    200: DevicesPublic;
};

export type devicesReadDevicesResponse = devicesReadDevicesResponses[keyof devicesReadDevicesResponses];

export type devicesCreateDeviceData = {
    body: DeviceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/devices/';
};

export type devicesCreateDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesCreateDeviceError = devicesCreateDeviceErrors[keyof devicesCreateDeviceErrors];

export type devicesCreateDeviceResponses = {
    /**
     * Successful Response
     */
    200: DeviceRegistrationInfo;
};

export type devicesCreateDeviceResponse = devicesCreateDeviceResponses[keyof devicesCreateDeviceResponses];

export type devicesDeleteDeviceData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/devices/{id}';
};

export type devicesDeleteDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesDeleteDeviceError = devicesDeleteDeviceErrors[keyof devicesDeleteDeviceErrors];

export type devicesDeleteDeviceResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type devicesDeleteDeviceResponse = devicesDeleteDeviceResponses[keyof devicesDeleteDeviceResponses];

export type devicesUpdateDeviceData = {
    body: DeviceUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/devices/{id}';
};

export type devicesUpdateDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesUpdateDeviceError = devicesUpdateDeviceErrors[keyof devicesUpdateDeviceErrors];

export type devicesUpdateDeviceResponses = {
    /**
     * Successful Response
     */
    200: DevicePublic;
};

export type devicesUpdateDeviceResponse = devicesUpdateDeviceResponses[keyof devicesUpdateDeviceResponses];

export type deviceRegisterDeviceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/device/register';
};

export type deviceRegisterDeviceResponses = {
    /**
     * Successful Response
     */
    200: DeviceHandshakePublic;
};

export type deviceRegisterDeviceResponse = deviceRegisterDeviceResponses[keyof deviceRegisterDeviceResponses];

export type deviceGetNextNoteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/device/notes/next';
};

export type deviceGetNextNoteResponses = {
    /**
     * Response Device-Get Next Note
     *
     * Successful Response
     */
    200: DeviceNotePublic | null;
};

export type deviceGetNextNoteResponse = deviceGetNextNoteResponses[keyof deviceGetNextNoteResponses];

export type deviceMarkNoteReceivedData = {
    body?: never;
    path: {
        /**
         * Delivery Id
         */
        delivery_id: string;
    };
    query?: never;
    url: '/api/v1/device/notes/{delivery_id}/received';
};

export type deviceMarkNoteReceivedErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type deviceMarkNoteReceivedError = deviceMarkNoteReceivedErrors[keyof deviceMarkNoteReceivedErrors];

export type deviceMarkNoteReceivedResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type deviceMarkNoteReceivedResponse = deviceMarkNoteReceivedResponses[keyof deviceMarkNoteReceivedResponses];

export type notesReadNotesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/notes/';
};

export type notesReadNotesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type notesReadNotesError = notesReadNotesErrors[keyof notesReadNotesErrors];

export type notesReadNotesResponses = {
    /**
     * Successful Response
     */
    200: NotesPublic;
};

export type notesReadNotesResponse = notesReadNotesResponses[keyof notesReadNotesResponses];

export type notesCreateNoteData = {
    body: NoteCreate;
    path?: never;
    query?: never;
    url: '/api/v1/notes/';
};

export type notesCreateNoteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type notesCreateNoteError = notesCreateNoteErrors[keyof notesCreateNoteErrors];

export type notesCreateNoteResponses = {
    /**
     * Successful Response
     */
    200: NotePublic;
};

export type notesCreateNoteResponse = notesCreateNoteResponses[keyof notesCreateNoteResponses];

export type notesReadInboxData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/notes/inbox';
};

export type notesReadInboxErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type notesReadInboxError = notesReadInboxErrors[keyof notesReadInboxErrors];

export type notesReadInboxResponses = {
    /**
     * Successful Response
     */
    200: NotesPublic;
};

export type notesReadInboxResponse = notesReadInboxResponses[keyof notesReadInboxResponses];

export type notesReadNoteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/notes/{id}';
};

export type notesReadNoteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type notesReadNoteError = notesReadNoteErrors[keyof notesReadNoteErrors];

export type notesReadNoteResponses = {
    /**
     * Successful Response
     */
    200: NoteDetailPublic;
};

export type notesReadNoteResponse = notesReadNoteResponses[keyof notesReadNoteResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
